title: "Tomb Raider Archive"
description: "Welcome to the Tomb Raider Archive!"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes settings
minimal_mistakes_skin: "default"

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/

# Author
author:
  name: "Tomb Raider Archive"
